# Generated by Django 4.2.2 on 2023-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos/', verbose_name='imagen')),
            ],
        ),
    ]
