# Generated by Django 4.2.2 on 2023-07-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='titulo',
        ),
    ]
